spring:
  application:
    name: apigateway

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

  data:
    redis:
      database: 0
      host: ${HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:secret_password}
      timeout: 60000

  security:
    oauth2:
      google:
        issuer: ${GOOGLE_AS_URI:https://accounts.google.com}
        jwk-uri: ${GOOGLE_AS_JWK_URI:https://www.googleapis.com/oauth2/v3/certs}
      insurance:
        issuer: ${INSURANCE_AS_URI:http://localhost:7070}
        jwk-uri: ${INSURANCE_AS_JWK_URI:http://localhost:7070/oauth2/jwks}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:*}
  rate-limit:
    user-profile-update:
      enabled: ${USER_PROFILE_UPDATE_RATE_LIMIT_ENABLED:true}
      max-requests: ${USER_PROFILE_UPDATE_RATE_LIMIT_MAX_REQUESTS:5}
      window: ${USER_PROFILE_UPDATE_RATE_LIMIT_WINDOW:1m}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

server:
  port: ${PORT:8080}
  tomcat:
    max-http-form-post-size: 30MB
    max-swallow-size: 30MB

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            server:
              webmvc: TRACE
          mvc: TRACE
        web:
          servlet: TRACE
          web: TRACE
