services:
  policy-service-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-policy_db}
    ports:
      - "${POSTGRES_PORT:-5436}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
