global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: spring-boot-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - service-discovery:8761
          - authorization-server:9000
          - user-service:8081
          - product-service:8082
          - pricing-service:8083
          - application-policy-service:8084
          - payment-service:8085
          - notification-service:8086
          - apigateway:8080

  - job_name: ai-model-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - ai-model-service:8000
